### ISSUE TITLE
problem with jsonata

### ISSUE THREAD

**Issue by francescoagati** [s1r-J/node-red-contrib-flow-asserter#4]
hello,
i try to do a test with jsonata that return a boolean expression. but the test fail always

here the flow example of my test

`[{"id":"72bfdf8d.4f187","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"ed0d4c60.3e167","type":"flow-asserter in","z":"72bfdf8d.4f187","name":"","testcases":[{"testId":0,"input":"{\"x\":\"aava\"}","inputType":"json","operator":"jsonata","assert":"x = \"AAVA\"","assertType":"jsonata"}],"flowasserterout":"3205fe50.6a0e62","x":168,"y":381,"wires":[["2134f76f.a779e8"],["ccb50cfe.dd80f"]]},{"id":"3205fe50.6a0e62","type":"flow-asserter out","z":"72bfdf8d.4f187","name":"s","x":448,"y":205,"wires":[["5b623413.af171c"]]},{"id":"ccb50cfe.dd80f","type":"debug","z":"72bfdf8d.4f187","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":333,"y":559,"wires":[]},{"id":"5b623413.af171c","type":"debug","z":"72bfdf8d.4f187","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":605,"y":358,"wires":[]},{"id":"322df857.dce3e8","type":"inject","z":"72bfdf8d.4f187","name":"","topic":"","payload":"{\"x\":\"aaaa\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":130,"y":112,"wires":[["2134f76f.a779e8"]]},{"id":"2134f76f.a779e8","type":"function","z":"72bfdf8d.4f187","name":"","func":"\nmsg.payload.x = msg.payload.x.toUpperCase()\n\nreturn msg;","outputs":1,"noerr":0,"x":219,"y":214,"wires":[["3205fe50.6a0e62","5b623413.af171c"]]}]`

**Comment by s1r-J** [comment]
@francescoagati 
Thank you for using my module.

I think that the cause of failing is the wrong jsonata expression.
`x` is the property of `payload`, so in jsonata exp you need to use `payload.x` instead of `x`.

I added a fixed testcase in following flow.

```
[{"id":"a47ef39e.6a6208","type":"flow-asserter in","z":"6a9e9041.790dd","name":"","testcases":[{"testId":0,"input":"{\"x\":\"aava\"}","inputType":"json","operator":"jsonata","assert":"x = \"AAVA\"","assertType":"jsonata"},{"testId":1,"input":"{\"x\":\"aava\"}","inputType":"json","operator":"jsonata","assert":"payload.x = \"AAVA\"","assertType":"jsonata"}],"flowasserterout":"586155dd.cd92ac","x":168,"y":381,"wires":[["e57a09ae.128b58"],["a4ce39c6.0fcb6"]]},{"id":"586155dd.cd92ac","type":"flow-asserter out","z":"6a9e9041.790dd","name":"s","x":448,"y":205,"wires":[["3b511e02.e4f952"]]},{"id":"a4ce39c6.0fcb6","type":"debug","z":"6a9e9041.790dd","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":333,"y":559,"wires":[]},{"id":"3b511e02.e4f952","type":"debug","z":"6a9e9041.790dd","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":605,"y":358,"wires":[]},{"id":"2a5c230c.23605c","type":"inject","z":"6a9e9041.790dd","name":"","topic":"","payload":"{\"x\":\"aaaa\"}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":130,"y":112,"wires":[["e57a09ae.128b58"]]},{"id":"e57a09ae.128b58","type":"function","z":"6a9e9041.790dd","name":"","func":"\nmsg.payload.x = msg.payload.x.toUpperCase()\n\nreturn msg;","outputs":1,"noerr":0,"x":219,"y":214,"wires":[["586155dd.cd92ac","3b511e02.e4f952"]]}]
```

**Comment by francescoagati** [comment]
really thanks i will try to test it
